name: chicago_ej
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - altair
  - shapely
  - matplotlib
  - jupyterlab
  - pip
  - numpy
  - rasterio
  - rasterstats
  - pyproj
  - fiona
  - rtree
  - jupyter

  - pip:
  - quarto
